name: Python Package CI

on:
  push:
    branches:
      - master

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace '3.x' with your desired Python version (e.g., '3.8', '3.9')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Build and package
        run: |
          python setup.py sdist

      - name: Publish to GitHub Packages
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
